### ISSUE TITLE
color names are wrong in the status bar/menu

### ISSUE THREAD

**Issue by RetroNick2020** [rchastain/velena#1]
I like how you implemented this. just that the status bar and menus doesn't match the actual color of game pieces. 

The menus and status bar refers to black and white players/turn but the actual game pieces are red and yellow.

have you compared this to an implementation that uses min/max. I forked a version of c4 in pure pascal. I am curious to know how that compares.

**Comment by rchastain** [comment]
Thank you for your interest in that project. Yes, you are right about colors. In my idea, white means "the player who plays first", independently of pieces actual color (as in chess).
I took a look at the Pascal c4. Nice little program.
For Velena, according to what its author says, it plays "perfectly".
I have on my HD another version (a Delphi project written by a French teacher, ported by me to Lazarus), using Minimax algorithm. I attach here in case you wish to take a look.
[connect4-lazarus-minmax.zip](https://github.com/rchastain/velena/files/7738979/connect4-lazarus-minmax.zip)

**Comment by RetroNick2020** [comment]
thanks for the attachment. I read these like books when i get a chance.

I also managed to compile the c source using Tiny C Compiler 0.9.27 -
Copyright (C) 2001-2006 Fabrice Bellard

I swapped your exe with the tiny c version and seems to work fine.

tcc CONNECT4.C ADJMTRX.C BINTREE.C BUILDOB.C CMDLINE.C DATABASE.C DUMMY.C
ERROR.C EVALUATE.C HEURIST.C IA_MAIN.C PBSOLVER.C  PLAYGAME.C PNSEARCH.C
WC.C -o connect4.exe

**Comment by rchastain** [comment]
> I also managed to compile the c source using Tiny C Compiler 0.9.27 - Copyright (C) 2001-2006 Fabrice Bellard I swapped your exe with the tiny c version and seems to work fine. tcc CONNECT4.C ADJMTRX.C BINTREE.C BUILDOB.C CMDLINE.C DATABASE.C DUMMY.C ERROR.C EVALUATE.C HEURIST.C IA_MAIN.C PBSOLVER.C PLAYGAME.C PNSEARCH.C WC.C -o connect4.exe

Interesting. But, be careful, I believe that Velena need to be compiled in 32-bit. In 64-bit it doesn't work correctly.
